Session 7 - Routing to Github Profile
gavandivya/NamasteReact pull request #8
Opened 2022-12-10 13:24 UTC by gavandivya

![image](https://user-images.githubusercontent.com/49062060/206857349-dea28173-0a06-4369-a3bb-2c13bb03cdd7.png)
Added Routing and displayed each users **Github Stats, Coding streak and Most used language** by them.

2022-12-11 06:47 UTC, Pujarini commented
Wow divya this is so good idea 🎉!

2022-12-11 07:05 UTC, Pujarini requested changes

2022-12-11 07:05 UTC, Pujarini commented on Lecture6(GithubAPI)/App.js
> +
Try to write the folder names with small letters.

2022-12-11 09:14 UTC, ap221882 reviewed
Everything good. Reviewed.

2022-12-11 09:14 UTC, ap221882 commented on Lecture6(GithubAPI)/App.js
>  import { createRoot } from "react-dom/client";
"Component" folder should be renamed to "components" or "Components", preferably "components".

2022-12-11 09:14 UTC, ap221882 commented on Lecture6(GithubAPI)/App.js
> +        path: "/",
You can use - 
```
{ index: true, element: <Index /> },
``` 
for the default Outlet when we don't provide it for the root path whose children we are routing.
refer: https://reactrouter.com/en/main/start/tutorial#index-routes

2022-12-11 09:14 UTC, ap221882 commented on Lecture6(GithubAPI)/Component/BodyComponent.js
> +        let githubdata = await Promise.all(githubUserNames.map(async (userName) => {
Nice trait to refine your code. Appreciated!

2022-12-11 09:14 UTC, ap221882 commented on Lecture6(GithubAPI)/Component/BodyComponent.js
>          if (!sessionStorage.getItem('teamData')) {
You can also in future remove items from session storage whose values give {message:"Not Found"}. Though here you're sure it will work, so nice.

2022-12-11 09:14 UTC, ap221882 commented on Lecture6(GithubAPI)/Component/ErrorComponent.js
> +import img from "../assets/error-icon.webp";
can name it error image

2022-12-11 09:55 UTC, gavandivya commented on Lecture6(GithubAPI)/App.js
> +        path: "/",
thanks a lot, helpful!

2022-12-11 10:08 UTC, gavandivya commented on Lecture6(GithubAPI)/Component/ErrorComponent.js
> +import img from "../assets/error-icon.webp";
done

2022-12-11 10:08 UTC, gavandivya commented on Lecture6(GithubAPI)/Component/ErrorComponent.js
> +import img from "../assets/error-icon.webp";
done

2022-12-11 10:31 UTC, gavandivya commented on Lecture6(GithubAPI)/App.js
> +
done

2022-12-11 10:32 UTC, gavandivya commented on Lecture6(GithubAPI)/App.js
>  import { createRoot } from "react-dom/client";
changes done thanks!

2022-12-12 12:07 UTC, merged

2022-12-13 13:38 UTC, roshantrivedi commented
Wow... nice work.